global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hyperledger_metrics'
    scrape_interval: 10s
    static_configs:
      - targets: [peer0.org1.example.com:7061, peer1.org1.example.com:7061, peer0.org2.example.com:7061, peer1.org2.example.com:7061, orderer1.example.com:7060, orderer2.example.com:7060, orderer3.example.com:7060]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
